.TH ubertooth\-debug 1 "March 2017" "Project Ubertooth" "User Commands"
.SH NAME
.PP
ubertooth\-debug(1) \- Classic Bluetooth discovery, sniffing, and decoding

.SH SYNOPSIS
.PP
.RS

.nf
ubertooth\-debug \-r <number>[,<number>[,...]]

.fi
.RE

.SH DESCRIPTION
.PP
ubertooth\-debug(1) is a tool for reading register values from the CC2400 chip
on Ubertooth One. It is primarily designed to assist firmware development but
may be of interest to curious hackers.

.SH OPTIONS
.PP
Options:
.IP \(bu 2
\fB\fC\-r <reg>[,<reg> [,[...]]]\fR :
Read one or more registers from the CC2400 on Ubertooth
.IP \(bu 2
\fB\fC\-r <start>\-<end>\fR :
Read a consecutive set of registers from the CC2400 on Ubertooth
.IP \(bu 2
\fB\fC\-v <0\-2>\fR :
Sets the level of verbosity, default is 1.
.IP \(bu 2
\fB\fC\-U<0\-7>\fR :
Which Ubertooth device to use

.SH EXAMPLES
.PP
To read the MANOR register, use:

.PP
.RS

.nf
ubertooth\-debug \-r 19

.fi
.RE

.PP
Registers can also be specified by name, the following will
also read the MANOR register:

.PP
.RS

.nf
ubertooth\-debug \-r %manor

.fi
.RE

.PP
Read a range of registers:

.PP
.RS

.nf
ubertooth\-debug \-r 19\-22

.fi
.RE

.PP
Dump all registers with:

.PP
.RS

.nf
ubertooth\-debug \-r 0x00\-0x70

.fi
.RE

.SH SEE ALSO
.PP
ubertooth(7): overview of Project Ubertooth

.SH AUTHOR
.PP
This manual page was written by Dominic Spill.

.SH COPYRIGHT
.PP
ubertooth\-debug(1) is Copyright (c) 2010\-2017. This tool is released under the
GPLv2. Refer to \fB\fCCOPYING\fR for further details.
